# Generated by Django 5.1.6 on 2025-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0009_alter_card_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_subscribe",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="pay_day",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
