# Generated by Django 5.1.6 on 2025-02-22 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0012_transactions_transaction_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
