# Generated by Django 5.1.6 on 2025-02-22 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0013_delete_transactions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ["-created"],
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
    ]
